name: Unit tests

on: [push, pull_request]

env:
  TEST_FOLDER: tests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          
      - name: Run npm install
        working-directory: ./${{env.TEST_FOLDER}}
        run: |
          npm install
        
      - name: Install jest
        working-directory: ./${{env.TEST_FOLDER}}
        run: |
          npm install jest
          
      - name: Install fetch
        working-directory: ./${{env.TEST_FOLDER}}
        run: |
           npm install node-fetch
          
      - name: Run tests
        working-directory: ./${{env.TEST_FOLDER}}
        run: |
          yarn jest
